# Generated by Django 5.0.1 on 2025-09-21 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
        ('surveys', '0004_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.question'),
        ),
    ]
