# Generated by Django 5.0.1 on 2025-09-21 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_alter_submissionanswer_question'),
        ('surveys', '0004_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionanswer',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.option'),
        ),
    ]
