# Generated by Django 5.0.1 on 2025-09-21 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_alter_submissionanswer_selected_option'),
        ('companies', '0005_add_lastcontact_model'),
        ('surveys', '0005_alter_option_option_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ibge_code', models.CharField(db_index=True, max_length=7, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('is_capital', models.BooleanField(default=False)),
                ('siafi_id', models.CharField(blank=True, max_length=4)),
                ('area_code', models.CharField(blank=True, max_length=2)),
                ('timezone', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'answers_city',
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='answers.city'),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=2, unique=True)),
                ('uf', models.CharField(db_index=True, max_length=2, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('region', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'answers_state',
                'indexes': [models.Index(fields=['region'], name='answers_sta_region_c07e09_idx'), models.Index(fields=['uf'], name='answers_sta_uf_6836bb_idx')],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='answers.state'),
        ),
        migrations.AddField(
            model_name='submission',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='answers.state'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['city'], name='answers_sub_city_id_0af74d_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['state'], name='answers_sub_state_i_ae10d6_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['state'], name='answers_cit_state_i_0e903f_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['ibge_code'], name='answers_cit_ibge_co_e96635_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['is_capital'], name='answers_cit_is_capi_c25c57_idx'),
        ),
    ]
