# Generated by Django 5.0.1 on 2025-08-20 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('surveys', '0002_survey_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='companies.company'),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Company',
                ),
            ],
            database_operations=[],
        ),
    ]
