# Generated by Django 5.0.1 on 2025-08-24 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_alter_survey_company_delete_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice')], default='text', max_length=32),
        ),
    ]
