# Generated by Django 5.0.1 on 2025-09-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option_type',
            field=models.CharField(choices=[('choice', 'Opção'), ('text', 'Texto')], default='choice', max_length=16),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Texto'), ('single_choice', 'Escolha única'), ('multiple_choice', 'Múltiplas escolhas')], default='text', max_length=32),
        ),
    ]
