# Generated by Django 5.0.1 on 2025-09-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companytoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='activated_at',
            field=models.DateTimeField(blank=True, help_text='Data de ativação do contrato', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('prospect', 'Prospect (Em análise)'), ('client', 'Cliente (Operando)')], default='prospect', help_text='Define se a empresa é prospect ou cliente ativo', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, help_text='Data de desativação do contrato', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Indica se a empresa tem contrato ativo (relacionado a vendas)'),
        ),
        migrations.AddField(
            model_name='company',
            name='notes',
            field=models.TextField(blank=True, help_text='Observações sobre a empresa'),
        ),
        migrations.AddField(
            model_name='company',
            name='payment_status',
            field=models.CharField(choices=[('active', 'Pagamento em dia'), ('overdue', 'Pagamento atrasado'), ('suspended', 'Suspenso por inadimplência')], default='active', help_text='Status do pagamento da empresa', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='payment_suspended_at',
            field=models.DateTimeField(blank=True, help_text='Data de suspensão por inadimplência', null=True),
        ),
    ]
