# Generated by Django 5.0.1 on 2025-09-08 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_add_company_status_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, help_text='Cidade', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='cnpj',
            field=models.CharField(blank=True, help_text='CNPJ da empresa (ex: 00.000.000/0000-00)', max_length=18),
        ),
        migrations.AddField(
            model_name='company',
            name='complement',
            field=models.CharField(blank=True, help_text='Complemento (apto, sala, etc.)', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF do responsável (ex: 000.000.000-00)', max_length=14),
        ),
        migrations.AddField(
            model_name='company',
            name='neighborhood',
            field=models.CharField(blank=True, help_text='Bairro', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='number',
            field=models.CharField(blank=True, help_text='Número', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, help_text='Telefone de contato (ex: 55 54 99992-0559)', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='postal_code',
            field=models.CharField(blank=True, help_text='CEP (ex: 00000-000)', max_length=9),
        ),
        migrations.AddField(
            model_name='company',
            name='responsible_person',
            field=models.CharField(blank=True, help_text='Nome do responsável pela empresa', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(blank=True, help_text='Estado (sigla)', max_length=2),
        ),
        migrations.AddField(
            model_name='company',
            name='street',
            field=models.CharField(blank=True, help_text='Rua/Avenida', max_length=255),
        ),
    ]
