# Generated by Django 5.0.1 on 2025-09-08 00:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_add_contact_and_address_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LastContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Data e hora do contato')),
                ('notes', models.TextField(help_text='Observações sobre o contato realizado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(limit_choices_to={'company_type': 'prospect'}, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Último Contato',
                'verbose_name_plural': 'Últimos Contatos',
                'ordering': ['-contact_date', '-created_at'],
            },
        ),
    ]
