# Generated by Django 5.0.1 on 2025-09-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_add_lastcontact_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='companytoken',
            name='access_token',
            field=models.TextField(blank=True, help_text='Access token JWT (armazenado apenas para exibição)'),
        ),
    ]
