# Generated by Django 5.0.1 on 2025-09-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_companytoken_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='companytoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Data de expiração do access token', null=True),
        ),
    ]
