# Generated by Django 5.0.1 on 2025-09-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_add_expires_at_to_companytoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='companytoken',
            name='refresh_token',
            field=models.TextField(blank=True, help_text='Refresh token JWT para renovação do access token'),
        ),
    ]
