# Generated by Django 5.0.1 on 2025-09-25 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_companytoken_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo da empresa para relatórios', null=True, upload_to='company_logos/'),
        ),
    ]
