# Generated by Django 5.0.1 on 2025-10-08 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_company_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='logo',
        ),
        migrations.CreateModel(
            name='CompanyAPIAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, help_text='Nome de usuário único para autenticação', max_length=150, unique=True)),
                ('password', models.CharField(help_text='Senha hash para autenticação', max_length=128)),
                ('label', models.CharField(blank=True, help_text='Rótulo descritivo para identificar a conta', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Define se a conta está ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, help_text='Data de desativação da conta', null=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Última vez que esta conta foi usada', null=True)),
                ('company', models.ForeignKey(help_text='Empresa associada a esta conta', on_delete=django.db.models.deletion.CASCADE, related_name='api_accounts', to='companies.company')),
            ],
            options={
                'verbose_name': 'Conta API da Empresa',
                'verbose_name_plural': 'Contas API das Empresas',
                'db_table': 'company_api_accounts',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
    ]
